name: WNC1
on:
  push:
    branches: [ master ]
  schedule:
  # - cron: "0 1 * * *"
   - cron: "4,14,24,34,44,54 * * * *"
  workflow_dispatch:
 
#xxx
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
     - name: Get IP
       run: |
          echo Get Ip Address
          curl -i  https://ipinfo.io/json
         
             
     - name: Start leech
       env:
          url: ${{ secrets.wncurl }}
       run: |         
          echo Download dll
          wget --output-document=netdll.zip $url 
          echo unzip
          unzip netdll.zip -d netdll
          sudo chmod -R +X netdll 
          cd netdll
          echo run.sh
          chmod +x run.sh
          sh ./run.sh
                  
     - name: Upload log
       uses: actions/upload-artifact@v2
       with:
          name: artifact-log
          path: netdll/logs
