name: WNC1
on:
  push:
    branches: [ master ]
  schedule:
  # - cron: "0 1 * * *"
   - cron: "4,14,24,34,44,54 * * * *"
  workflow_dispatch:
 
#xxx
jobs:
  build:
    runs-on: ubuntu-18.04 #ubuntu-latest
    steps:      
     - name: Get IP
       run: |
          echo Get Ip Address
          curl -i  https://ipinfo.io/json
     - name: Cleanup Disk
       run: |
          echo Cleanup
          sudo rm -rf /var/lib/docker
          sudo rm -rf /usr/local/lib/android
          sudo apt remove -y kubectl mysql-server-core-5.7 postgresql-13 mysql-server-5.7 mongodb-org-shell mongodb-org-mongos  linux-azure-5.4-headers-5.4.0-1039 dotnet-runtime-3.0 dotnet-runtime-3.1  libpython3.6-dev mongodb-org-server podman snapd mono-devel moby-engine moby-containerd  llvm-6.0-dev powershell dotnet-sdk-3.0 llvm-9-dev llvm-8-dev dotnet-sdk-3.1 adoptopenjdk-8-hotspot firefox google-chrome-stable hhvm adoptopenjdk-11-hotspot adoptopenjdk-12-hotspot google-cloud-sdk azure-cli ghc-8.10.3 ghc-8.8.4
          echo cleanup completed! ================
          df -h
     - name: Download zip
       env:
          url: ${{ secrets.wncurl }}
       run: |
          echo Download dll
          wget -q --output-document=netdll.zip $url 
          echo unzip..........
          unzip netdll.zip -d netdll
          sudo chmod -R +X netdll 
          cd netdll
          echo awk................
          awk '{ sub("\r$", ""); print }' ./run.sh > ./run-unix.sh	
          awk '{ sub("\r$", ""); print }' ./config.sh > ./config-unix.sh
     - name: Config
       run: |
          cd netdll
          chmod +x ./config-unix.sh	   
          chmod +x ./run-unix.sh	   
          echo ./config-unix.sh..........
          sh ./config-unix.sh
     - name: Start leech
       run: |
          cd netdll       
          echo ./run-unix.sh..........
          sh ./run-unix.sh
     - name: Upload log
       uses: actions/upload-artifact@v2
       with:
          name: artifact-log
          path: netdll/logs
